
//=======================================================
//  This code is generated by Terasic System Builder
//=======================================================

module week_08b(

	//////////// CLOCK //////////
	input 		          		CLOCK_50,

	//////////// SEG7 //////////
	output		     [6:0]		HEX0,
	output		     [6:0]		HEX1,
	output		     [6:0]		HEX2,
	output		     [6:0]		HEX3,
	output		     [6:0]		HEX4,
	output		     [6:0]		HEX5,

	//////////// KEY //////////
	input 		     [3:0]		KEY,

	//////////// LED //////////
	output		     [9:0]		LEDR,

	//////////// SW //////////
	input 		     [9:0]		SW
);



//=======================================================
//  REG/WIRE declarations
//=======================================================
	wire	[3:0] address;  // left two digits
	wire	[7:0] data_out; // middle two digits
	wire	[7:0] data_in;  // right two digits
	
	wire [3:0] KEY_PRESSED; // keys filtered by find_rise.v
	
	
	

//=======================================================
//  Functional coding
//=======================================================

	segment7 digit0 (1'b1,data_in[3:0],HEX0);
	segment7 digit1 (1'b1,data_in[7:4],HEX1);
	segment7 digit2 (1'b1,data_out[3:0],HEX2);
	segment7 digit3 (1'b1,data_out[7:4],HEX3);
	segment7 digit4 (1'b1,address[3:0],HEX4);
	segment7 digit5 (1'b1,4'h0,HEX5);

	assign address = SW[9:6];
	assign data_in = {2'b00,SW[5:0]};

	assign LEDR[9:0] = SW[9:0];
	

	find_rise u1(
		.clk(CLOCK_50),
		.in(~KEY[0]),
		.out(KEY_PRESSED[0])
	);

	find_rise u2(
		.clk(CLOCK_50),
		.in(~KEY[1]),
		.out(KEY_PRESSED[1])
	);
	find_rise u3(
		.clk(CLOCK_50),
		.in(~KEY[2]),
		.out(KEY_PRESSED[2])
	);
	find_rise u4(
		.clk(CLOCK_50),
		.in(~KEY[3]),
		.out(KEY_PRESSED[3])
	);
	
	// **************************************************
	// TASK : 
	//   build the module in the file rammodule ram 
	// **************************************************

	// ram
	ram #(.DATA_WIDTH(8), .ADDR_WIDTH(4)) ram1(
		.data_in(data_in),
		.data_out(data_out),
		.addr(adress),
		.re(KEY_PRESSED[0]),
		.we(KEY_PRESSED[1]),
		.clk(CLOCK_50),
	);

		
endmodule
