
//=======================================================
//  This code is generated by Terasic System Builder
//=======================================================

module week_04(

	//////////// CLOCK //////////
	input 		          		CLOCK2_50,
	input 		          		CLOCK3_50,
	input 		          		CLOCK4_50,
	input 		          		CLOCK_50,

	//////////// SEG7 //////////
	output		     [6:0]		HEX0,
	output		     [6:0]		HEX1,
	output		     [6:0]		HEX2,
	output		     [6:0]		HEX3,
	output		     [6:0]		HEX4,
	output		     [6:0]		HEX5,

	//////////// KEY //////////
	input 		     [3:0]		KEY,

	//////////// LED //////////
	output		     [9:0]		LEDR,

	//////////// SW //////////
	input 		     [9:0]		SW
);



//=======================================================
//  REG/WIRE declarations
//=======================================================
	wire [7:0] NUM1;  // left two digits
	wire [7:0] NUM2;	// middle two digits
	wire [7:0] NUM3;  // right two digits
	

//=======================================================
//  Functional coding
//=======================================================

	segment7 digit0 (NUM3[3:0],HEX0);
	segment7 digit1 (NUM3[7:4],HEX1);
	segment7 digit2 (NUM2[3:0],HEX2);
	segment7 digit3 (NUM2[7:4],HEX3);
	segment7 digit4 (NUM1[3:0],HEX4);
	segment7 digit5 (NUM1[7:4],HEX5);

	assign NUM1 = {4'b0000,SW[9:6]};
	assign NUM2 = {4'b0000,SW[5:2]};
	assign LEDR = SW;

   // TASK2: Build calculating block	
	assign NUM3 = 0;

endmodule
